import React, { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import {
  FileText,
  Download,
  ExternalLink,
  ShieldCheck,
  Search,
} from "lucide-react";
import {
  PageHeader,
  Card,
  Button,
  StatusBadge,
  LoadingState,
  EmptyState,
} from "../components/ui";
import AnalystApi from "../api/analystApi";
import type { AnalystCase } from "../types/analyst";
import { getApiError } from "../utils/getApiError";

const ReportsPage: React.FC = () => {
  const [cases, setCases] = useState<AnalystCase[]>([]);
  const [selectedCase, setSelectedCase] = useState<AnalystCase | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [search, setSearch] = useState("");

  const loadReports = async () => {
    setLoading(true);
    setError(null);
    try {
      const res = await AnalystApi.fetchFeed({ page: 1, limit: 50 });
      // Cases that have a generated report
      const reportedCases = res.data.filter((c) => c.report && c.report.trim() !== "");
      setCases(reportedCases);
      if (reportedCases.length > 0) {
        setSelectedCase(reportedCases[0]);
      }
    } catch (err: any) {
      setError(getApiError(err, "Failed to load incident reports"));
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadReports();
  }, []);

  const handleDownload = (caseObj: AnalystCase) => {
    if (!caseObj.report) return;
    const blob = new Blob([caseObj.report], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `axiom-incident-report-case-${caseObj.id}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const filtered = cases.filter(
    (c) =>
      c.title.toLowerCase().includes(search.toLowerCase()) ||
      c.id.toString().includes(search)
  );

  if (loading) return <LoadingState label="Loading incident reports…" />;

  return (
    <div className="space-y-6 animate-fade-in bg-app-bg min-h-screen -m-6 p-6 sm:p-8">
      <PageHeader
        title="Incident Reports & Compliance Records"
        crumbs={[{ label: "Overview", to: "/" }, { label: "Reports" }]}
        description="Automated markdown incident reports generated by AXIOM AI upon decision authorization."
      />

      {error && (
        <div className="p-4 rounded-xl bg-red-50 border border-red-200 text-sm text-red-600 font-medium">
          {error}
        </div>
      )}

      {cases.length === 0 ? (
        <Card className="bg-white border-line-subtle shadow-card">
          <EmptyState
            title="No incident reports generated yet"
            description="Reports are automatically generated when a human approves or declines a case decision."
          />
        </Card>
      ) : (
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          {/* Reports Sidebar List */}
          <div className="space-y-3">
            <div className="relative">
              <Search size={16} className="absolute left-3.5 top-1/2 -translate-y-1/2 text-slate-400" />
              <input
                type="text"
                placeholder="Search reports by case # or title..."
                value={search}
                onChange={(e) => setSearch(e.target.value)}
                className="w-full bg-white border border-line-subtle rounded-xl pl-10 pr-4 py-2.5 text-xs text-slate-800 placeholder-slate-400 focus:outline-none focus:border-blue-500 font-medium shadow-card"
              />
            </div>

            <div className="space-y-2 max-h-[600px] overflow-y-auto pr-1">
              {filtered.map((c) => {
                const isSelected = selectedCase?.id === c.id;
                return (
                  <button
                    key={c.id}
                    onClick={() => setSelectedCase(c)}
                    className={`w-full text-left p-4 rounded-2xl border transition ${
                      isSelected
                        ? "bg-blue-50/80 border-blue-300 shadow-card"
                        : "bg-white border-line-subtle hover:border-slate-300 shadow-card"
                    }`}
                  >
                    <div className="flex items-center justify-between mb-1">
                      <span className="text-xs font-bold text-blue-600 font-mono">
                        Case #{c.id}
                      </span>
                      <StatusBadge
                        tone={c.decision === "approved" ? "success" : "neutral"}
                        label={c.decision}
                      />
                    </div>
                    <p className="text-xs font-bold text-slate-900 truncate">{c.title}</p>
                    <p className="text-[10px] text-slate-400 mt-1 font-mono">
                      {c.decided_at ? new Date(c.decided_at).toLocaleDateString() : "Generated"}
                    </p>
                  </button>
                );
              })}
            </div>
          </div>

          {/* Main Report View */}
          <div className="lg:col-span-2">
            {selectedCase ? (
              <Card className="bg-white border-line-subtle shadow-card space-y-4">
                <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 pb-4 border-b border-slate-100">
                  <div>
                    <h2 className="text-lg font-bold text-slate-900 font-display">
                      Report: Case #{selectedCase.id}
                    </h2>
                    <p className="text-xs text-slate-500 mt-0.5">{selectedCase.title}</p>
                  </div>
                  <div className="flex items-center gap-2">
                    <Link to={`/case/${selectedCase.id}`}>
                      <Button variant="secondary" size="sm">
                        <ExternalLink size={14} className="mr-1.5" />
                        View Case Workspace
                      </Button>
                    </Link>
                    <Button
                      variant="primary"
                      size="sm"
                      onClick={() => handleDownload(selectedCase)}
                      className="bg-blue-600 hover:bg-blue-700 text-white font-bold"
                    >
                      <Download size={14} className="mr-1.5" />
                      Download Markdown
                    </Button>
                  </div>
                </div>

                <div className="flex items-center gap-2 px-3.5 py-2 rounded-xl bg-slate-50 border border-slate-200 text-xs text-slate-600 font-mono">
                  <ShieldCheck size={14} className="text-emerald-600" />
                  <span>Immutable Audit Signed by AXIOM AI Reasoner ({selectedCase.analysis?.model || "Claude-Sonnet"})</span>
                </div>

                <pre className="p-5 rounded-2xl bg-[#0e1320] text-slate-200 border border-slate-800 text-xs whitespace-pre-wrap font-mono leading-relaxed overflow-x-auto shadow-navy">
                  {selectedCase.report}
                </pre>
              </Card>
            ) : (
              <Card className="bg-white border-line-subtle shadow-card">
                <EmptyState title="Select a report to view" description="Click any incident report on the left to read the complete markdown audit report." />
              </Card>
            )}
          </div>
        </div>
      )}
    </div>
  );
};

export default ReportsPage;
