"""Phase 48: Evidence bundle PDF with chain-of-custody + hash verification.

Renders a tamper-evident evidence bundle PDF including:
- Case metadata
- Chain-of-custody timeline with per-entry hash and prev_hash
- Hash chain verification status
- Audit chain integrity
- SOC2 control mapping (if provided)
- Generation timestamp, actor, org

Uses reportlab, pageCompression=0 for greppability in tests.

Honest limitations documented in PDF footer:
- Hash chain is SHA256(prev_hash|content), not Merkle tree, no external timestamp authority
- PDF itself is not signed; hash verification is for audit log chain, not PDF integrity
- Retention deletes old logs; checkpoint preserves last hash but not full history
"""

from __future__ import annotations

import io
from datetime import datetime, timezone
from typing import Any, Dict, List

def _ensure_reportlab():
    try:
        from reportlab.lib.pagesizes import letter
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import inch
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
        from reportlab.lib import colors
        return letter, getSampleStyleSheet, ParagraphStyle, inch, SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, colors
    except ImportError as exc:
        raise RuntimeError("PDF export needs reportlab (pip install reportlab)") from exc


def _strip(text: str) -> str:
    if not text:
        return "-"
    # remove markdown-ish
    import re
    text = re.sub(r"\*\*(.+?)\*\*", r"\1", text)
    text = re.sub(r"`(.+?)`", r"\1", text)
    return text.strip()[:1000]


def render_evidence_bundle_pdf(
    case_data: Dict[str, Any],
    chain_of_custody: Dict[str, Any],
    audit_verification: Dict[str, Any] | None = None,
    soc2_bundle: Dict[str, Any] | None = None,
    generated_by: str = "system",
    org_id: int | None = None,
) -> bytes:
    """Render evidence bundle PDF.

    Args:
        case_data: serialized case dict
        chain_of_custody: result of get_case_chain_of_custody (has chain list with hash/prev_hash)
        audit_verification: result of verify_audit_chain
        soc2_bundle: optional SOC2 evidence bundle
        generated_by: actor username
        org_id: org id for header

    Returns PDF bytes starting with %PDF.
    """
    (
        letter,
        getSampleStyleSheet,
        ParagraphStyle,
        inch,
        SimpleDocTemplate,
        Paragraph,
        Spacer,
        Table,
        TableStyle,
        PageBreak,
        colors,
    ) = _ensure_reportlab()

    buf = io.BytesIO()
    case_id = case_data.get("id", "?")
    title = case_data.get("title", "")

    doc = SimpleDocTemplate(
        buf,
        pagesize=letter,
        rightMargin=0.6 * inch,
        leftMargin=0.6 * inch,
        topMargin=0.6 * inch,
        bottomMargin=0.6 * inch,
        title=f"NOCTRA Evidence Bundle - Case #{case_id}",
        author="NOCTRA Compliance",
        pageCompression=0,
    )

    styles = getSampleStyleSheet()
    h1 = styles["Heading1"]
    h1.fontSize = 16
    h2 = styles["Heading2"]
    h2.fontSize = 13
    h3 = styles["Heading3"]
    normal = styles["Normal"]
    normal.fontSize = 9
    normal.leading = 12
    mono = ParagraphStyle("mono", parent=normal, fontName="Courier", fontSize=7, leading=9)
    small = ParagraphStyle("small", parent=normal, fontSize=8, textColor=colors.HexColor("#555555"))
    italic = ParagraphStyle("italic", parent=normal, fontName="Helvetica-Oblique", textColor=colors.HexColor("#333333"))

    story: List[Any] = []

    # Header
    story.append(Paragraph(f"Evidence Bundle — Case #{case_id}", h1))
    story.append(Paragraph(f"{_strip(title)}", h2))
    story.append(Spacer(1, 0.1 * inch))
    meta_table = [
        ["Case ID", str(case_id)],
        ["Title", _strip(title)],
        ["Status", str(case_data.get("status", "-"))],
        ["Severity", str(case_data.get("severity", "-"))],
        ["Generated At", datetime.now(timezone.utc).isoformat()],
        ["Generated By", generated_by],
        ["Org ID", str(org_id) if org_id is not None else "-"],
    ]
    t = Table(meta_table, colWidths=[1.5 * inch, 5.0 * inch])
    t.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#f0f0f0")),
                ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
                ("FONTSIZE", (0, 0), (-1, -1), 9),
                ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#cccccc")),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ]
        )
    )
    story.append(t)
    story.append(Spacer(1, 0.2 * inch))

    # Chain-of-custody
    story.append(Paragraph("Chain-of-Custody", h2))
    story.append(Paragraph("Each entry is hashed as SHA256(prev_hash|timestamp|kind|label|detail). Any tampering breaks the chain.", small))
    story.append(Spacer(1, 0.1 * inch))

    chain = chain_of_custody.get("chain", []) if chain_of_custody else []
    last_hash = chain_of_custody.get("last_hash", "-") if chain_of_custody else "-"

    if not chain:
        story.append(Paragraph("No chain-of-custody entries found.", normal))
    else:
        # Table header
        header = ["#", "Timestamp", "Kind", "Label", "Hash (first 16)", "Prev (first 16)"]
        rows = [header]
        for idx, entry in enumerate(chain, start=1):
            at = str(entry.get("at", "-"))[:19]
            kind = str(entry.get("kind", "-"))[:12]
            label = _strip(str(entry.get("label", "-")))[:30]
            h = str(entry.get("hash", "-"))[:16]
            ph = str(entry.get("prev_hash", "-"))[:16]
            rows.append([str(idx), at, kind, label, h, ph])

        # Limit to 100 rows for PDF size, note truncation
        truncated = False
        if len(rows) > 101:
            rows = rows[:101]
            truncated = True

        col_widths = [0.3 * inch, 1.1 * inch, 0.7 * inch, 2.0 * inch, 1.1 * inch, 1.1 * inch]
        t2 = Table(rows, colWidths=col_widths, repeatRows=1)
        t2.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#222222")),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                    ("FONTSIZE", (0, 0), (-1, -1), 7),
                    ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#cccccc")),
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                    ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f9f9f9")]),
                ]
            )
        )
        story.append(t2)
        if truncated:
            story.append(Paragraph(f"... truncated, total {len(chain)} entries, showing first 100", small))
        story.append(Spacer(1, 0.1 * inch))
        story.append(Paragraph(f"Last hash: {last_hash}", mono))
        story.append(Paragraph(f"Chain verified: {chain_of_custody.get('verified', False)}", small))

    story.append(Spacer(1, 0.2 * inch))

    # Audit chain verification
    if audit_verification:
        story.append(Paragraph("Audit Log Integrity", h2))
        audit_table = [
            ["Total Checked", str(audit_verification.get("total_checked", "-"))],
            ["Verified", str(audit_verification.get("verified", "-"))],
            ["Chain Valid", str(audit_verification.get("chain_valid", "-"))],
            ["Broken At", str(audit_verification.get("broken_at") or "-")],
            ["Broken Details", _strip(str(audit_verification.get("broken_details") or "-"))],
            ["Last Hash", str(audit_verification.get("last_hash", "-"))[:64]],
        ]
        t3 = Table(audit_table, colWidths=[1.5 * inch, 5.0 * inch])
        t3.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#e8f4f8")),
                    ("FONTSIZE", (0, 0), (-1, -1), 8),
                    ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#cccccc")),
                ]
            )
        )
        story.append(t3)
        story.append(Spacer(1, 0.2 * inch))

    # SOC2 controls if present
    if soc2_bundle:
        story.append(Paragraph("SOC2 Controls Evidence", h2))
        controls = soc2_bundle.get("controls", {})
        for cid, cdata in controls.items():
            story.append(Paragraph(f"{cid}: {cdata.get('control_name', '-')}", h3))
            story.append(Paragraph(_strip(cdata.get("description", "")), small))
            story.append(Paragraph(f"Evidence count: {cdata.get('evidence_count', 0)}", small))
            samples = cdata.get("sample_logs", [])[:3]
            if samples:
                sample_rows = [["Action", "Actor", "Timestamp"]]
                for s in samples:
                    sample_rows.append([s.get("action", "-"), s.get("actor", "-"), str(s.get("timestamp", "-"))[:19]])
                st = Table(sample_rows, colWidths=[1.5 * inch, 1.5 * inch, 2.0 * inch])
                st.setStyle(
                    TableStyle(
                        [
                            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#f0f0f0")),
                            ("FONTSIZE", (0, 0), (-1, -1), 7),
                            ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#dddddd")),
                        ]
                    )
                )
                story.append(st)
            story.append(Spacer(1, 0.1 * inch))

    # Footer honesty notes
    story.append(PageBreak())
    story.append(Paragraph("Honest Limitations & Chain-of-Custody Notes", h2))
    notes = [
        "1. Hash chain is SHA256(prev_hash|action|actor|resource|details|timestamp), not a Merkle tree.",
        "2. No external timestamp authority (RFC3161) — timestamps are server-generated.",
        "3. PDF itself is not cryptographically signed; verify audit chain via /api/v1/compliance/audit/verify endpoint.",
        "4. Retention policy deletes logs older than LOG_RETENTION_DAYS but keeps a checkpoint hash — full history not recoverable after retention.",
        "5. Chain-of-custody covers case timeline events (status changes, analyst actions, comments) as recorded in DB; external evidence not included.",
        "6. If reportlab is missing, endpoint returns 501.",
        "7. This bundle is generated on-demand from live DB rows; it is not stored immutably unless exported and stored externally.",
    ]
    for note in notes:
        story.append(Paragraph(note, small))
        story.append(Spacer(1, 0.05 * inch))

    story.append(Spacer(1, 0.2 * inch))
    story.append(Paragraph(f"Generated at {datetime.now(timezone.utc).isoformat()} by {generated_by} — NOCTRA Compliance Module", italic))

    doc.build(story)
    return buf.getvalue()
