import React, { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import {
  FileText,
  Download,
  ExternalLink,
  ShieldCheck,
  Search,
} from "lucide-react";
import {
  PageHeader,
  Card,
  Button,
  StatusBadge,
  SkeletonChart,
  SkeletonList,
  EmptyState,
} from "../../../components/ui";
import AnalystApi from "../../../api/analystApi";
import type { AnalystCase } from "../../../types/analyst";
import { getApiError } from "../../../utils/getApiError";

const ReportsPage: React.FC = () => {
  const [cases, setCases] = useState<AnalystCase[]>([]);
  const [selectedCase, setSelectedCase] = useState<AnalystCase | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [search, setSearch] = useState("");

  const loadReports = async () => {
    setLoading(true);
    setError(null);
    try {
      const res = await AnalystApi.fetchFeed({ page: 1, limit: 50 });
      // Cases that have a generated report
      const reportedCases = res.data.filter((c) => c.report && c.report.trim() !== "");
      setCases(reportedCases);
      if (reportedCases.length > 0) {
        setSelectedCase(reportedCases[0]);
      }
    } catch (err: any) {
      setError(getApiError(err, "Failed to load incident reports"));
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadReports();
    localStorage.setItem("noctra_visited_reports", "1");
  }, []);

  const handleDownload = (caseObj: AnalystCase) => {
    if (!caseObj.report) return;
    const blob = new Blob([caseObj.report], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `noctra-report-case-${caseObj.id}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const filtered = cases.filter(
    (c) =>
      c.title.toLowerCase().includes(search.toLowerCase()) ||
      c.id.toString().includes(search)
  );

  if (loading) {
    return (
      <div className="space-y-6 animate-fade-in bg-app-bg min-h-screen -m-6 p-6 sm:p-8">
        <PageHeader
          title="Incident Reports"
          crumbs={[{ label: "Overview", to: "/" }, { label: "Reports" }]}
          description="Markdown incident reports, generated by NOCTRA when a decision is authorized."
        />
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          <SkeletonList rows={6} />
          <SkeletonChart className="lg:col-span-2 min-h-[420px]" />
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-6 animate-fade-in bg-app-bg min-h-screen -m-6 p-6 sm:p-8">
      <PageHeader
        title="Incident Reports"
        crumbs={[{ label: "Overview", to: "/" }, { label: "Reports" }]}
        description="Markdown incident reports, generated by NOCTRA when a decision is authorized."
      />

      {error && (
        <div
          role="alert"
          className="p-4 rounded-xl bg-status-critical/10 border border-status-critical/30 text-sm text-status-critical font-medium"
        >
          {error}
        </div>
      )}

      {cases.length === 0 ? (
        <Card className="bg-app-surface border-line-subtle shadow-card">
          <EmptyState
            title="No incident reports generated yet"
            description="Reports are automatically generated when a human approves or declines a case decision."
          />
        </Card>
      ) : (
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          {/* Reports Sidebar List */}
          <div className="space-y-3">
            <div className="relative">
              <Search size={16} className="absolute left-3.5 top-1/2 -translate-y-1/2 text-content-tertiary" />
              <input
                type="text"
                placeholder="Search reports by case # or title..."
                value={search}
                onChange={(e) => setSearch(e.target.value)} className="w-full bg-app-surface border border-line-subtle rounded-2xl pl-10 pr-4 py-2.5 text-xs text-content-primary placeholder-content-tertiary focus:outline-none focus:border-accent-primary font-medium shadow-card"
              />
            </div>

            <div className="space-y-2 max-h-[600px] overflow-y-auto pr-1">
              {filtered.map((c) => {
                const isSelected = selectedCase?.id === c.id;
                return (
                  <button
                    key={c.id}
                    onClick={() => setSelectedCase(c)}
                    className={`w-full text-left p-4 rounded-2xl border transition ${
                      isSelected
                        ? "bg-accent-primary/10 border-accent-primary/40 shadow-card"
                        : "bg-app-surface border-line-subtle hover:border-line-bright shadow-card"
                    }`}
                  >
                    <div className="flex items-center justify-between mb-1">
                      <span className="text-xs font-bold text-accent-primary font-mono">
                        Case #{c.id}
                      </span>
                      <StatusBadge
                        tone={c.decision === "approved" ? "success" : "neutral"}
                        label={c.decision}
                      />
                    </div>
                    <p className="text-xs font-bold text-content-primary truncate">{c.title}</p>
                    <p className="text-[10px] text-content-tertiary mt-1 font-mono">
                      {c.decided_at ? new Date(c.decided_at).toLocaleDateString() : "Generated"}
                    </p>
                  </button>
                );
              })}
            </div>
          </div>

          {/* Main Report View */}
          <div className="lg:col-span-2">
            {selectedCase ? (
              <Card className="bg-app-surface border-line-subtle shadow-card space-y-4">
                <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 pb-4 border-b border-line-subtle">
                  <div>
                    <h2 className="text-lg font-bold text-content-primary font-display">
                      Report: Case #{selectedCase.id}
                    </h2>
                    <p className="text-xs text-content-tertiary mt-0.5">{selectedCase.title}</p>
                  </div>
                  <div className="flex items-center gap-2">
                    <Link to={`/case/${selectedCase.id}`}>
                      <Button variant="secondary" size="sm">
                        <ExternalLink size={14} className="mr-1.5" />
                        View Case Workspace
                      </Button>
                    </Link>
                    <Button
                      variant="primary"
                      size="sm"
                      onClick={() => handleDownload(selectedCase)}
                      
                    >
                      <Download size={14} className="mr-1.5" />
                      Download Markdown
                    </Button>
                  </div>
                </div>

                <div className="flex items-center gap-2 px-3.5 py-2 rounded-xl bg-app-subtle border border-line-subtle text-xs text-content-secondary font-mono">
                  <ShieldCheck size={14} className="text-status-success" />
                  <span>
                    Decision record — report generated by NOCTRA ({selectedCase.analysis?.model || "built-in reasoning engine"})
                  </span>
                </div>

                <pre className="night p-5 rounded-2xl bg-app-navy text-content-secondary border border-app-void text-xs whitespace-pre-wrap font-mono leading-relaxed overflow-x-auto shadow-navy">
                  {selectedCase.report}
                </pre>
              </Card>
            ) : (
              <Card className="bg-app-surface border-line-subtle shadow-card">
                <EmptyState title="Select a report to view" description="Click any incident report on the left to read the complete markdown audit report." />
              </Card>
            )}
          </div>
        </div>
      )}
    </div>
  );
};

export default ReportsPage;
